import type { Metadata } from "next";
import {  Geist_Mono, Host_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Beams from "@/Reactbits/Beams/Beams";
import Footer from "@/components/Footer";

const hostGrotesk = Host_Grotesk({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CampusVault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ position: "relative", minHeight: "100vh" }}
        className={`${hostGrotesk.variable} ${geistMono.variable} antialiased`}
      >
        <div
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%",
            zIndex: -1,
            pointerEvents: "none",
          }}
        >
          <Beams
            beamWidth={5}
            beamHeight={20}
            beamNumber={20}
            lightColor="#C60606"
            speed={2}
            noiseIntensity={1}
            scale={0.2}
            rotation={45}
          />
        </div>
        <main>
          <Navbar />
          {children}
          <Footer/>
        </main>
      </body>
    </html>
  );
}

